### PR TITLE
A second, manual way to resolve conflicting changes

### PR DESCRIPTION
**Pull request by MikeTheGreat**
I don't know if this is useful to include here (and/or if you want to brush up on the writing - after this I'm going to fall into bed :)   ), but I found this to be a useful strategy for resolving conflicting file versions.

### CODE REVIEW

**Comment by nevenz** [comment]
Cool, can you just fix:

- "DropBox" -> "Dropbox"
- "remove notebooks" -> "remote notebooks"

Thanks!

**Comment by MikeTheGreat** [comment]
I'd be happy to make these changes!
One question: how does one make changes to a pull request?  

I found an 'Edit' button for the specific file (under the 'Files changed' tab), but it's inactive (greyed out) and when I mouse over it it says "You must be signed in [I am] and have push access to the patch-1 branch to make changes".  Clicking it doesn't do anything.
(Neither Google generally nor StackOverflow specifically are saving me,either)

**Comment by nevenz** [comment]
I see the same (greyed out button with the same message).

Perhaps you have to **fork the repo** and start making changes there. Updating pull request in general should be a matter of committing to the same branch.

**Comment by MikeTheGreat** [comment]
I think you're right - I forked this, changed it, submitted a pull request, and was then able to use that button to update my pull request.

I tweaked the language to give it a quick overview, and to use a better way of diff'ing the files (if you rename the original file then Orgzly will add that to it's list of notebooks when you sync, so moving the file to a different directory is better)

**Pull request closed without merging**
