### PR TITLE
Rewrote the quick start guide.

### PR DESCRIPTION
**Pull request by appetrosyan**
Updated some of the older references, and tried to improve the style and grammar. Please let me know if there are any typos, or mistakes.

### CODE REVIEW

**Comment by nevenz** [comment]
Thanks, but the idea with that notebook is to be very short and to the point, each note describing one of the possibly not so obvious actions or features.

**Comment by appetrosyan** [comment]
I can cut it down to be shorter than the original. About half the notes describe the already intuitive controls, so if you want short and to the point I can arrange that.

**Comment by nevenz** [comment]
I think it OK the way it is right now. It starts with super-basic thing - click note to open it - so user can immediately see what the notebook is about. Then it outlines the rest of features.

Also, this notebook is being translated on [Crowdin](https://crowdin.com/project/orgzly). So I'm reluctant to do any changes to it, as modified lines would require people to translate them again.

Thanks again though.

**Comment by appetrosyan** [comment]
As you wish. Word of advice, though: you can argue that it does its job, but at least look into the grammar. I understand that English isn't your native language and it shows, so even without changing the structure, please consider using proper syntax and grammar.

**Comment by nevenz** [comment]
> but at least look into the grammar. I understand that English isn't your native language and it shows, so even without changing the structure, please consider using proper syntax and grammar.

PR for fixing those is welcomed.

**Pull request closed without merging**
